# Generated by Django 3.2 on 2022-04-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220421_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Psku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
