# Generated by Django 3.2 on 2022-04-30 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_product_psku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('Productid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
            options={
                'db_table': 'Product_Gallary',
            },
        ),
    ]
