# Generated by Django 3.2 on 2022-05-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20220501_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Ptotal',
            field=models.IntegerField(default=0),
        ),
    ]
