# Generated by Django 3.2 on 2022-05-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_product_ptotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Ptotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
