# Generated by Django 3.2 on 2022-05-03 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0011_auto_20220503_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_mode', models.CharField(choices=[('cod', 'cod'), ('paytm', 'paytm')], default='cod', max_length=255)),
                ('ostatus', models.CharField(choices=[('created', 'Created'), ('shipped', 'Shipped'), ('paid', 'Paid')], default='created', max_length=255)),
                ('ocontactno', models.CharField(default='1', max_length=10)),
                ('oaddress', models.CharField(blank=True, max_length=255)),
                ('odate', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='app1.cartadd')),
                ('user', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oquant', models.IntegerField(default=1)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
                ('product', models.ManyToManyField(to='app1.Product')),
            ],
            options={
                'db_table': 'orderdetails',
            },
        ),
    ]
