# Generated by Django 3.2 on 2022-05-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20220503_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checksum',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
